image:
  file: .gitpod.Dockerfile

tasks:
  - before: pip install --upgrade pip
    init: pip install -r requirements.txt
    command: python setup.py develop

vscode:
  extensions:
    - ms-python.python
    - ms-azuretools.vscode-docker
